version: '3'
services:
  db:
    image: postgres
    container_name: pgdb
    ports: 
      - "5432:5432"
    environment:  
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=newsPortal
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - newsPortal
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@sample.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    networks:
      - newsPortal
networks:
  newsPortal:
    name: newsPortal
    driver: bridge

    
